name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: golang-1.14.4-alpine
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test the code
      run: make test
